{
    'name': "Jal Aqua CRM",
    'version': "15.0",
    'summary': """ Jal Aqua CRM """,
    'description': """ Jal Aqua CRM """,
    'author': "",
    'company': "",
    'maintainer': "",
    'website': "",
    'category': 'Tools',
    'depends': ['base','crm','sale_management','purchase','stock','l10n_in','sale_stock','sale_crm'],
    'data': [
        'data/sequence.xml',
        'data/inherit_res_lang.xml',
        'security/ir.model.access.csv',
        'security/record_rule.xml',
        'security/security_group.xml',

        'report/paper_formate.xml',
        'report/report_sale_domestic.xml',
        'report/report_sale_international.xml',
        'report/report_sale_proforma.xml',

        'views/inherit_crm.xml',
        'views/inherit_sale.xml',
        'views/inherit_purchase.xml',
        'views/inherit_product.xml',
        'views/inherit_users.xml',
        'views/inherit_sale_team.xml',
        'views/inherit_address.xml',
        'views/product_shipping_mst.xml',
        'views/inherit_partner.xml',
        'views/sale_misc_mst.xml',
        'views/product_misc_mst.xml',
        'views/purchase_requisite.xml',
        # 'views/inherit_company.xml',
        'views/master_menu.xml',

    ],
    # 'images': ['static/description/banner.png'],
    'license': "AGPL-3",
    'installable': True,
    'application': False
}
