from . import inherit_crm
from . import inherit_sale
from . import inherit_purchase
from . import inherit_product
from . import inherit_users
from . import inherit_sale_team
from . import inherit_address
from . import product_shipping_mst
from . import inherit_partner
from . import sale_misc_mst
from . import inherit_company
from . import product_misc_mst
from . import purchase_requisite