{
    'name': "Jal Production",
    'version': "15.0",
    'summary': """ Jal Production """,
    'description': """ Jal Production """,
    'author': "",
    'company': "",
    'maintainer': "",
    'website': "",
    'category': 'Tools',
    'depends': ['base','stock','jal_crm','hr','master'],
    'data': [
        'data/sequence.xml',
        'data/attribute_value.xml',
        'security/security_group.xml',
        'security/ir.model.access.csv',
        'security/record_rule.xml',

        'wizards/production_exel_wiz.xml',

        'report/quality_barcode_report.xml',
        'report/material_requisition_report.xml',
        'report/paper_formate.xml',

        'views/production.xml',
        'views/quality.xml',
        'views/shift_mst.xml',
        'views/inherit_product.xml',
        'views/quality_parameter_mst.xml',
        'views/inherit_product_attribute.xml',
        'views/material_requisition.xml',
        'views/inherit_sale.xml',
        'views/inherit_purchase.xml',
        'views/inherit_user.xml',
        'views/inherit_stock.xml',
        'views/dryer_mst.xml',
        'views/purchase_quality.xml',
        'views/jal_mrp_production.xml',
        'views/product_transformation.xml',
        'views/constipation_material.xml',
        'views/master_menu.xml',

    ],
    'license': "AGPL-3",
    'installable': True,
    'application': False
}
